
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package edu.uta.spl;

import scala.collection.immutable.*;
import scala.Tuple2;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SplParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SplParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SplParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SplParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\120\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\005\004\000\002\005\005" +
    "\000\002\006\007\000\002\006\006\000\002\006\013\000" +
    "\002\016\002\000\002\016\004\000\002\017\007\000\002" +
    "\017\005\000\002\017\002\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\005\000\002\011\006\000" +
    "\002\011\004\000\002\011\005\000\002\011\005\000\002" +
    "\011\010\000\002\011\005\000\002\015\005\000\002\015" +
    "\003\000\002\015\002\000\002\021\005\000\002\021\003" +
    "\000\002\010\004\000\002\010\005\000\002\007\005\000" +
    "\002\007\006\000\002\007\005\000\002\007\006\000\002" +
    "\007\006\000\002\007\007\000\002\007\011\000\002\007" +
    "\014\000\002\007\007\000\002\007\004\000\002\007\003" +
    "\000\002\007\004\000\002\007\003\000\002\020\004\000" +
    "\002\020\002\000\002\022\005\000\002\022\003\000\002" +
    "\012\003\000\002\012\006\000\002\012\005\000\002\012" +
    "\005\000\002\023\007\000\002\023\005\000\002\013\003" +
    "\000\002\013\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\005\000\002" +
    "\004\005\000\002\004\006\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\034\004\016\014\022\020\005\023\024\024" +
    "\013\026\011\032\023\033\007\034\012\037\020\040\027" +
    "\041\010\063\017\001\002\000\004\055\247\001\002\000" +
    "\006\016\uffd5\055\uffd5\001\002\000\026\004\016\020\005" +
    "\023\024\024\013\026\011\032\023\033\007\034\012\041" +
    "\010\063\017\001\002\000\004\061\237\001\002\000\004" +
    "\061\233\001\002\000\026\004\016\020\005\023\024\024" +
    "\013\026\011\032\023\033\007\034\012\041\010\063\017" +
    "\001\002\000\036\004\072\005\070\006\102\007\074\011" +
    "\066\016\uffd3\021\071\030\100\043\064\045\067\055\uffd3" +
    "\061\065\063\073\065\075\001\002\000\004\061\223\001" +
    "\002\000\004\002\000\001\002\000\004\002\222\001\002" +
    "\000\014\017\uffce\057\uffce\060\uffce\061\217\065\uffce\001" +
    "\002\000\034\004\016\014\022\020\005\023\024\024\013" +
    "\026\011\032\023\033\007\034\012\037\020\040\027\041" +
    "\010\063\017\001\002\000\004\004\212\001\002\000\006" +
    "\002\ufffe\064\ufffe\001\002\000\004\004\202\001\002\000" +
    "\004\061\177\001\002\000\004\061\164\001\002\000\012" +
    "\017\162\057\104\060\105\065\103\001\002\000\004\055" +
    "\160\001\002\000\004\004\030\001\002\000\006\017\ufff8" +
    "\054\032\001\002\000\004\017\063\001\002\000\022\004" +
    "\040\011\035\012\036\022\043\025\033\035\037\061\034" +
    "\063\041\001\002\000\020\017\uffb9\055\uffb9\056\uffb9\062" +
    "\uffb9\063\uffb9\064\uffb9\066\uffb9\001\002\000\022\004\040" +
    "\011\035\012\036\022\043\025\033\035\037\061\034\063" +
    "\041\001\002\000\004\065\053\001\002\000\020\017\uffb6" +
    "\055\uffb6\056\uffb6\062\uffb6\063\uffb6\064\uffb6\066\uffb6\001" +
    "\002\000\020\017\uffb7\055\uffb7\056\uffb7\062\uffb7\063\uffb7" +
    "\064\uffb7\066\uffb7\001\002\000\020\017\uffb2\055\uffb2\056" +
    "\uffb2\062\uffb2\063\uffb2\064\uffb2\066\uffb2\001\002\000\006" +
    "\004\044\064\ufff4\001\002\000\006\017\ufff7\063\ufff7\001" +
    "\002\000\020\017\uffb8\055\uffb8\056\uffb8\062\uffb8\063\uffb8" +
    "\064\uffb8\066\uffb8\001\002\000\004\054\047\001\002\000" +
    "\004\064\046\001\002\000\020\017\uffb5\055\uffb5\056\uffb5" +
    "\062\uffb5\063\uffb5\064\uffb5\066\uffb5\001\002\000\022\004" +
    "\040\011\035\012\036\022\043\025\033\035\037\061\034" +
    "\063\041\001\002\000\010\056\051\062\ufff5\064\ufff5\001" +
    "\002\000\010\004\044\062\ufff4\064\ufff4\001\002\000\006" +
    "\062\ufff6\064\ufff6\001\002\000\022\004\040\011\035\012" +
    "\036\022\043\025\033\035\037\061\034\063\041\001\002" +
    "\000\004\066\055\001\002\000\020\017\uffb3\055\uffb3\056" +
    "\uffb3\062\uffb3\063\uffb3\064\uffb3\066\uffb3\001\002\000\004" +
    "\062\062\001\002\000\006\056\060\062\uffe2\001\002\000" +
    "\022\004\040\011\035\012\036\022\043\025\033\035\037" +
    "\061\034\063\041\001\002\000\004\062\uffe3\001\002\000" +
    "\020\017\uffb4\055\uffb4\056\uffb4\062\uffb4\063\uffb4\064\uffb4" +
    "\066\uffb4\001\002\000\032\004\072\005\070\006\102\007" +
    "\074\011\066\021\071\030\100\043\064\045\067\061\065" +
    "\063\073\065\075\001\002\000\032\004\uffc8\005\uffc8\006" +
    "\uffc8\007\uffc8\011\uffc8\021\uffc8\030\uffc8\043\uffc8\045\uffc8" +
    "\061\uffc8\063\uffc8\065\uffc8\001\002\000\034\004\072\005" +
    "\070\006\102\007\074\011\066\021\071\030\100\043\064" +
    "\045\067\061\065\062\uffe4\063\073\065\075\001\002\000" +
    "\004\061\151\001\002\000\054\010\ufff0\013\ufff0\015\ufff0" +
    "\016\ufff0\027\ufff0\031\ufff0\036\ufff0\042\ufff0\043\ufff0\044" +
    "\ufff0\046\ufff0\047\ufff0\050\ufff0\051\ufff0\052\ufff0\053\ufff0" +
    "\055\ufff0\056\ufff0\062\ufff0\064\ufff0\066\ufff0\001\002\000" +
    "\054\010\ufff1\013\ufff1\015\ufff1\016\ufff1\027\ufff1\031\ufff1" +
    "\036\ufff1\042\ufff1\043\ufff1\044\ufff1\046\ufff1\047\ufff1\050" +
    "\ufff1\051\ufff1\052\ufff1\053\ufff1\055\ufff1\056\ufff1\062\ufff1" +
    "\064\ufff1\066\ufff1\001\002\000\054\010\uffef\013\uffef\015" +
    "\uffef\016\uffef\027\uffef\031\uffef\036\uffef\042\uffef\043\uffef" +
    "\044\uffef\046\uffef\047\uffef\050\uffef\051\uffef\052\uffef\053" +
    "\uffef\055\uffef\056\uffef\062\uffef\064\uffef\066\uffef\001\002" +
    "\000\064\010\uffce\013\uffce\015\uffce\016\uffce\027\uffce\031" +
    "\uffce\036\uffce\042\uffce\043\uffce\044\uffce\046\uffce\047\uffce" +
    "\050\uffce\051\uffce\052\uffce\053\uffce\055\uffce\056\uffce\057" +
    "\uffce\060\uffce\061\146\062\uffce\064\uffce\065\uffce\066\uffce" +
    "\001\002\000\004\004\137\001\002\000\054\010\ufff2\013" +
    "\ufff2\015\ufff2\016\ufff2\027\ufff2\031\ufff2\036\ufff2\042\ufff2" +
    "\043\ufff2\044\ufff2\046\ufff2\047\ufff2\050\ufff2\051\ufff2\052" +
    "\ufff2\053\ufff2\055\ufff2\056\ufff2\062\ufff2\064\ufff2\066\ufff2" +
    "\001\002\000\034\004\072\005\070\006\102\007\074\011" +
    "\066\021\071\030\100\043\064\045\067\061\065\063\073" +
    "\065\075\066\uffe4\001\002\000\032\004\072\005\070\006" +
    "\102\007\074\011\066\021\071\030\100\043\064\045\067" +
    "\061\065\063\073\065\075\001\002\000\036\010\111\015" +
    "\122\027\115\031\126\042\117\043\112\044\123\046\125" +
    "\047\127\050\121\051\124\052\120\053\116\055\ufffb\001" +
    "\002\000\032\004\uffc7\005\uffc7\006\uffc7\007\uffc7\011\uffc7" +
    "\021\uffc7\030\uffc7\043\uffc7\045\uffc7\061\uffc7\063\uffc7\065" +
    "\uffc7\001\002\000\062\010\uffee\013\uffee\015\uffee\016\uffee" +
    "\027\uffee\031\uffee\036\uffee\042\uffee\043\uffee\044\uffee\046" +
    "\uffee\047\uffee\050\uffee\051\uffee\052\uffee\053\uffee\055\uffee" +
    "\056\uffee\057\104\060\105\062\uffee\064\uffee\065\103\066" +
    "\uffee\001\002\000\054\010\ufff3\013\ufff3\015\ufff3\016\ufff3" +
    "\027\ufff3\031\ufff3\036\ufff3\042\ufff3\043\ufff3\044\ufff3\046" +
    "\ufff3\047\ufff3\050\ufff3\051\ufff3\052\ufff3\053\ufff3\055\ufff3" +
    "\056\ufff3\062\ufff3\064\ufff3\066\ufff3\001\002\000\032\004" +
    "\072\005\070\006\102\007\074\011\066\021\071\030\100" +
    "\043\064\045\067\061\065\063\073\065\075\001\002\000" +
    "\004\006\107\001\002\000\004\004\106\001\002\000\064" +
    "\010\uffcc\013\uffcc\015\uffcc\016\uffcc\017\uffcc\027\uffcc\031" +
    "\uffcc\036\uffcc\042\uffcc\043\uffcc\044\uffcc\046\uffcc\047\uffcc" +
    "\050\uffcc\051\uffcc\052\uffcc\053\uffcc\055\uffcc\056\uffcc\057" +
    "\uffcc\060\uffcc\062\uffcc\064\uffcc\065\uffcc\066\uffcc\001\002" +
    "\000\064\010\uffcb\013\uffcb\015\uffcb\016\uffcb\017\uffcb\027" +
    "\uffcb\031\uffcb\036\uffcb\042\uffcb\043\uffcb\044\uffcb\046\uffcb" +
    "\047\uffcb\050\uffcb\051\uffcb\052\uffcb\053\uffcb\055\uffcb\056" +
    "\uffcb\057\uffcb\060\uffcb\062\uffcb\064\uffcb\065\uffcb\066\uffcb" +
    "\001\002\000\036\010\111\015\122\027\115\031\126\042" +
    "\117\043\112\044\123\046\125\047\127\050\121\051\124" +
    "\052\120\053\116\066\113\001\002\000\032\004\uffc1\005" +
    "\uffc1\006\uffc1\007\uffc1\011\uffc1\021\uffc1\030\uffc1\043\uffc1" +
    "\045\uffc1\061\uffc1\063\uffc1\065\uffc1\001\002\000\032\004" +
    "\uffc5\005\uffc5\006\uffc5\007\uffc5\011\uffc5\021\uffc5\030\uffc5" +
    "\043\uffc5\045\uffc5\061\uffc5\063\uffc5\065\uffc5\001\002\000" +
    "\064\010\uffcd\013\uffcd\015\uffcd\016\uffcd\017\uffcd\027\uffcd" +
    "\031\uffcd\036\uffcd\042\uffcd\043\uffcd\044\uffcd\046\uffcd\047" +
    "\uffcd\050\uffcd\051\uffcd\052\uffcd\053\uffcd\055\uffcd\056\uffcd" +
    "\057\uffcd\060\uffcd\062\uffcd\064\uffcd\065\uffcd\066\uffcd\001" +
    "\002\000\032\004\072\005\070\006\102\007\074\011\066" +
    "\021\071\030\100\043\064\045\067\061\065\063\073\065" +
    "\075\001\002\000\032\004\uffc2\005\uffc2\006\uffc2\007\uffc2" +
    "\011\uffc2\021\uffc2\030\uffc2\043\uffc2\045\uffc2\061\uffc2\063" +
    "\uffc2\065\uffc2\001\002\000\032\004\uffbe\005\uffbe\006\uffbe" +
    "\007\uffbe\011\uffbe\021\uffbe\030\uffbe\043\uffbe\045\uffbe\061" +
    "\uffbe\063\uffbe\065\uffbe\001\002\000\032\004\uffc6\005\uffc6" +
    "\006\uffc6\007\uffc6\011\uffc6\021\uffc6\030\uffc6\043\uffc6\045" +
    "\uffc6\061\uffc6\063\uffc6\065\uffc6\001\002\000\032\004\uffbf" +
    "\005\uffbf\006\uffbf\007\uffbf\011\uffbf\021\uffbf\030\uffbf\043" +
    "\uffbf\045\uffbf\061\uffbf\063\uffbf\065\uffbf\001\002\000\032" +
    "\004\uffbb\005\uffbb\006\uffbb\007\uffbb\011\uffbb\021\uffbb\030" +
    "\uffbb\043\uffbb\045\uffbb\061\uffbb\063\uffbb\065\uffbb\001\002" +
    "\000\032\004\uffc3\005\uffc3\006\uffc3\007\uffc3\011\uffc3\021" +
    "\uffc3\030\uffc3\043\uffc3\045\uffc3\061\uffc3\063\uffc3\065\uffc3" +
    "\001\002\000\032\004\uffc4\005\uffc4\006\uffc4\007\uffc4\011" +
    "\uffc4\021\uffc4\030\uffc4\043\uffc4\045\uffc4\061\uffc4\063\uffc4" +
    "\065\uffc4\001\002\000\032\004\uffba\005\uffba\006\uffba\007" +
    "\uffba\011\uffba\021\uffba\030\uffba\043\uffba\045\uffba\061\uffba" +
    "\063\uffba\065\uffba\001\002\000\032\004\uffbd\005\uffbd\006" +
    "\uffbd\007\uffbd\011\uffbd\021\uffbd\030\uffbd\043\uffbd\045\uffbd" +
    "\061\uffbd\063\uffbd\065\uffbd\001\002\000\032\004\uffc0\005" +
    "\uffc0\006\uffc0\007\uffc0\011\uffc0\021\uffc0\030\uffc0\043\uffc0" +
    "\045\uffc0\061\uffc0\063\uffc0\065\uffc0\001\002\000\032\004" +
    "\uffbc\005\uffbc\006\uffbc\007\uffbc\011\uffbc\021\uffbc\030\uffbc" +
    "\043\uffbc\045\uffbc\061\uffbc\063\uffbc\065\uffbc\001\002\000" +
    "\054\010\111\013\uffea\015\122\016\uffea\027\115\031\126" +
    "\036\uffea\042\117\043\112\044\123\046\125\047\127\050" +
    "\121\051\124\052\120\053\116\055\uffea\056\uffea\062\uffea" +
    "\064\uffea\066\uffea\001\002\000\054\010\111\013\uffeb\015" +
    "\122\016\uffeb\027\115\031\126\036\uffeb\042\117\043\112" +
    "\044\123\046\125\047\127\050\121\051\124\052\120\053" +
    "\116\055\uffeb\056\uffeb\062\uffeb\064\uffeb\066\uffeb\001\002" +
    "\000\004\066\136\001\002\000\042\010\111\015\122\027" +
    "\115\031\126\042\117\043\112\044\123\046\125\047\127" +
    "\050\121\051\124\052\120\053\116\056\134\062\uffe5\066" +
    "\uffe5\001\002\000\036\004\072\005\070\006\102\007\074" +
    "\011\066\021\071\030\100\043\064\045\067\061\065\062" +
    "\uffe4\063\073\065\075\066\uffe4\001\002\000\006\062\uffe6" +
    "\066\uffe6\001\002\000\054\010\uffed\013\uffed\015\uffed\016" +
    "\uffed\027\uffed\031\uffed\036\uffed\042\uffed\043\uffed\044\uffed" +
    "\046\uffed\047\uffed\050\uffed\051\uffed\052\uffed\053\uffed\055" +
    "\uffed\056\uffed\062\uffed\064\uffed\066\uffed\001\002\000\004" +
    "\017\142\001\002\000\004\064\141\001\002\000\054\010" +
    "\uffe7\013\uffe7\015\uffe7\016\uffe7\027\uffe7\031\uffe7\036\uffe7" +
    "\042\uffe7\043\uffe7\044\uffe7\046\uffe7\047\uffe7\050\uffe7\051" +
    "\uffe7\052\uffe7\053\uffe7\055\uffe7\056\uffe7\062\uffe7\064\uffe7" +
    "\066\uffe7\001\002\000\032\004\072\005\070\006\102\007" +
    "\074\011\066\021\071\030\100\043\064\045\067\061\065" +
    "\063\073\065\075\001\002\000\040\010\111\015\122\027" +
    "\115\031\126\042\117\043\112\044\123\046\125\047\127" +
    "\050\121\051\124\052\120\053\116\056\144\064\uffc9\001" +
    "\002\000\004\004\137\001\002\000\004\064\uffca\001\002" +
    "\000\034\004\072\005\070\006\102\007\074\011\066\021" +
    "\071\030\100\043\064\045\067\061\065\062\uffe4\063\073" +
    "\065\075\001\002\000\004\062\150\001\002\000\054\010" +
    "\uffec\013\uffec\015\uffec\016\uffec\027\uffec\031\uffec\036\uffec" +
    "\042\uffec\043\uffec\044\uffec\046\uffec\047\uffec\050\uffec\051" +
    "\uffec\052\uffec\053\uffec\055\uffec\056\uffec\062\uffec\064\uffec" +
    "\066\uffec\001\002\000\032\004\072\005\070\006\102\007" +
    "\074\011\066\021\071\030\100\043\064\045\067\061\065" +
    "\063\073\065\075\001\002\000\036\010\111\015\122\027" +
    "\115\031\126\042\117\043\112\044\123\046\125\047\127" +
    "\050\121\051\124\052\120\053\116\056\153\001\002\000" +
    "\032\004\072\005\070\006\102\007\074\011\066\021\071" +
    "\030\100\043\064\045\067\061\065\063\073\065\075\001" +
    "\002\000\036\010\111\015\122\027\115\031\126\042\117" +
    "\043\112\044\123\046\125\047\127\050\121\051\124\052" +
    "\120\053\116\062\155\001\002\000\054\010\uffe8\013\uffe8" +
    "\015\uffe8\016\uffe8\027\uffe8\031\uffe8\036\uffe8\042\uffe8\043" +
    "\uffe8\044\uffe8\046\uffe8\047\uffe8\050\uffe8\051\uffe8\052\uffe8" +
    "\053\uffe8\055\uffe8\056\uffe8\062\uffe8\064\uffe8\066\uffe8\001" +
    "\002\000\004\062\157\001\002\000\054\010\uffe9\013\uffe9" +
    "\015\uffe9\016\uffe9\027\uffe9\031\uffe9\036\uffe9\042\uffe9\043" +
    "\uffe9\044\uffe9\046\uffe9\047\uffe9\050\uffe9\051\uffe9\052\uffe9" +
    "\053\uffe9\055\uffe9\056\uffe9\062\uffe9\064\uffe9\066\uffe9\001" +
    "\002\000\032\002\uffe1\004\016\020\005\023\024\024\013" +
    "\026\011\032\023\033\007\034\012\041\010\063\017\064" +
    "\uffe1\001\002\000\006\002\uffe0\064\uffe0\001\002\000\032" +
    "\004\072\005\070\006\102\007\074\011\066\021\071\030" +
    "\100\043\064\045\067\061\065\063\073\065\075\001\002" +
    "\000\040\010\111\015\122\016\uffdf\027\115\031\126\042" +
    "\117\043\112\044\123\046\125\047\127\050\121\051\124" +
    "\052\120\053\116\055\uffdf\001\002\000\004\004\165\001" +
    "\002\000\004\017\166\001\002\000\032\004\072\005\070" +
    "\006\102\007\074\011\066\021\071\030\100\043\064\045" +
    "\067\061\065\063\073\065\075\001\002\000\036\010\111" +
    "\015\122\027\115\031\126\036\170\042\117\043\112\044" +
    "\123\046\125\047\127\050\121\051\124\052\120\053\116" +
    "\001\002\000\032\004\072\005\070\006\102\007\074\011" +
    "\066\021\071\030\100\043\064\045\067\061\065\063\073" +
    "\065\075\001\002\000\040\010\111\013\173\015\122\027" +
    "\115\031\126\042\117\043\112\044\123\046\125\047\127" +
    "\050\121\051\124\052\120\053\116\062\uffd1\001\002\000" +
    "\004\062\175\001\002\000\032\004\072\005\070\006\102" +
    "\007\074\011\066\021\071\030\100\043\064\045\067\061" +
    "\065\063\073\065\075\001\002\000\036\010\111\015\122" +
    "\027\115\031\126\042\117\043\112\044\123\046\125\047" +
    "\127\050\121\051\124\052\120\053\116\062\uffd2\001\002" +
    "\000\026\004\016\020\005\023\024\024\013\026\011\032" +
    "\023\033\007\034\012\041\010\063\017\001\002\000\006" +
    "\016\uffd8\055\uffd8\001\002\000\034\004\072\005\070\006" +
    "\102\007\074\011\066\021\071\030\100\043\064\045\067" +
    "\061\065\062\uffe4\063\073\065\075\001\002\000\004\062" +
    "\201\001\002\000\006\016\uffdb\055\uffdb\001\002\000\004" +
    "\061\203\001\002\000\006\004\044\062\ufff4\001\002\000" +
    "\004\062\205\001\002\000\006\054\032\063\ufff8\001\002" +
    "\000\004\063\207\001\002\000\034\004\016\014\022\020" +
    "\005\023\024\024\013\026\011\032\023\033\007\034\012" +
    "\037\020\040\027\041\010\063\017\001\002\000\004\064" +
    "\211\001\002\000\004\055\ufff9\001\002\000\004\017\213" +
    "\001\002\000\022\004\040\011\035\012\036\022\043\025" +
    "\033\035\037\061\034\063\041\001\002\000\004\055\ufffa" +
    "\001\002\000\004\064\216\001\002\000\006\016\uffdd\055" +
    "\uffdd\001\002\000\034\004\072\005\070\006\102\007\074" +
    "\011\066\021\071\030\100\043\064\045\067\061\065\062" +
    "\uffe4\063\073\065\075\001\002\000\004\062\221\001\002" +
    "\000\006\016\uffde\055\uffde\001\002\000\004\002\001\001" +
    "\002\000\032\004\072\005\070\006\102\007\074\011\066" +
    "\021\071\030\100\043\064\045\067\061\065\063\073\065" +
    "\075\001\002\000\036\010\111\015\122\027\115\031\126" +
    "\042\117\043\112\044\123\046\125\047\127\050\121\051" +
    "\124\052\120\053\116\062\225\001\002\000\026\004\016" +
    "\020\005\023\024\024\013\026\011\032\023\033\007\034" +
    "\012\041\010\063\017\001\002\000\006\016\227\055\uffda" +
    "\001\002\000\026\004\016\020\005\023\024\024\013\026" +
    "\011\032\023\033\007\034\012\041\010\063\017\001\002" +
    "\000\006\016\uffd9\055\uffd9\001\002\000\040\010\111\015" +
    "\122\016\uffd4\027\115\031\126\042\117\043\112\044\123" +
    "\046\125\047\127\050\121\051\124\052\120\053\116\055" +
    "\uffd4\001\002\000\006\016\uffd6\055\uffd6\001\002\000\032" +
    "\004\072\005\070\006\102\007\074\011\066\021\071\030" +
    "\100\043\064\045\067\061\065\063\073\065\075\001\002" +
    "\000\036\010\111\015\122\027\115\031\126\042\117\043" +
    "\112\044\123\046\125\047\127\050\121\051\124\052\120" +
    "\053\116\062\235\001\002\000\026\004\016\020\005\023" +
    "\024\024\013\026\011\032\023\033\007\034\012\041\010" +
    "\063\017\001\002\000\006\016\uffd7\055\uffd7\001\002\000" +
    "\004\004\240\001\002\000\014\056\uffce\057\uffce\060\uffce" +
    "\062\uffce\065\uffce\001\002\000\014\056\244\057\104\060" +
    "\105\062\uffcf\065\103\001\002\000\004\062\243\001\002" +
    "\000\006\016\uffdc\055\uffdc\001\002\000\004\004\240\001" +
    "\002\000\004\062\uffd0\001\002\000\006\002\uffff\064\uffff" +
    "\001\002\000\034\004\ufffd\014\022\020\ufffd\023\ufffd\024" +
    "\ufffd\026\ufffd\032\ufffd\033\ufffd\034\ufffd\037\020\040\027" +
    "\041\ufffd\063\ufffd\001\002\000\026\004\ufffc\020\ufffc\023" +
    "\ufffc\024\ufffc\026\ufffc\032\ufffc\033\ufffc\034\ufffc\041\ufffc" +
    "\063\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\020\002\014\003\013\005\005\006\003\007" +
    "\025\010\020\012\024\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\007\025\010\245\012\024\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\007\231\012\024" +
    "\001\001\000\010\011\230\012\100\013\075\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\003\214\005\005\006\003\007\025\010" +
    "\020\012\024\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\016\030\001\001\000\002\001\001\000\004\004\041\001" +
    "\001\000\002\001\001\000\006\004\056\021\055\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\017\044\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\047\001\001\000\002\001\001" +
    "\000\004\017\051\001\001\000\002\001\001\000\004\004" +
    "\053\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\004\056\021\060\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\011\076" +
    "\012\100\013\075\001\001\000\002\001\001\000\012\011" +
    "\132\012\100\013\075\015\155\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\023\137\001\001\000\002\001\001" +
    "\000\012\011\132\012\100\013\075\015\131\001\001\000" +
    "\010\011\130\012\100\013\075\001\001\000\004\014\113" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\011\107\012\100\013\075\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\113\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\011\127\012\100\013" +
    "\075\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\113\001" +
    "\001\000\004\014\113\001\001\000\002\001\001\000\004" +
    "\014\113\001\001\000\012\011\132\012\100\013\075\015" +
    "\134\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\011" +
    "\142\012\100\013\075\001\001\000\004\014\113\001\001" +
    "\000\004\023\144\001\001\000\002\001\001\000\012\011" +
    "\132\012\100\013\075\015\146\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\011\151\012\100\013\075\001" +
    "\001\000\004\014\113\001\001\000\010\011\153\012\100" +
    "\013\075\001\001\000\004\014\113\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\007\025" +
    "\010\160\012\024\001\001\000\002\001\001\000\010\011" +
    "\162\012\100\013\075\001\001\000\004\014\113\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\011\166\012" +
    "\100\013\075\001\001\000\004\014\113\001\001\000\010" +
    "\011\170\012\100\013\075\001\001\000\006\014\113\020" +
    "\171\001\001\000\002\001\001\000\010\011\173\012\100" +
    "\013\075\001\001\000\004\014\113\001\001\000\006\007" +
    "\175\012\024\001\001\000\002\001\001\000\012\011\132" +
    "\012\100\013\075\015\177\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\203\001\001" +
    "\000\002\001\001\000\004\016\205\001\001\000\002\001" +
    "\001\000\016\003\207\005\005\006\003\007\025\010\020" +
    "\012\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\213\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\011\132\012" +
    "\100\013\075\015\217\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\011\223\012\100\013" +
    "\075\001\001\000\004\014\113\001\001\000\006\007\225" +
    "\012\024\001\001\000\002\001\001\000\006\007\227\012" +
    "\024\001\001\000\002\001\001\000\004\014\113\001\001" +
    "\000\002\001\001\000\010\011\233\012\100\013\075\001" +
    "\001\000\004\014\113\001\001\000\006\007\235\012\024" +
    "\001\001\000\002\001\001\000\006\012\240\022\241\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\012\240\022\244\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\005\247\006\003" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SplParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SplParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SplParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    static int[] tokens = {
      sym.error, sym.ID, sym.STRING_LITERAL, sym.INTEGER_LITERAL, sym.FLOAT_LITERAL,
      sym.AND, sym.ARRAY, sym.BOOLEAN, sym.BY, sym.DEF, sym.DIV, sym.ELSE, sym.EQUAL, sym.EXIT, sym.FALSE,
      sym.FLOAT, sym.FOR, sym.IF, sym.INT, sym.LOOP, sym.MOD,
      sym.NOT, sym.OR, sym.PRINT, sym.READ, sym.RETURN, sym.STRING, sym.TO, sym.TYPE, sym.VAR, sym.WHILE,
      sym.PLUS, sym.MINUS, sym.TIMES, sym.TRUE,
      sym.LT, sym.LEQ, sym.GT, sym.GEQ, sym.EQ, sym.NEQ, sym.COLON, sym.SEMI,
      sym.COMMA, sym.SHARP, sym.DOT, sym.LP, sym.RP, sym.LB, sym.RB, sym.LSB, sym.RSB
    };

    static String[] token_names = {
      "error", "ID", "STRING_LITERAL", "INTEGER_LITERAL", "FLOAT_LITERAL",
      "AND &&", "ARRAY", "BOOLEAN", "BY", "DEF", "DIV /", "ELSE", "EQUAL", "EXIT", "FALSE",
      "FLOAT", "FOR", "IF", "INT", "LOOP", "MOD %",
      "NOT", "OR ||", "PRINT", "READ", "RETURN", "STRING", "TO", "TYPE", "VAR", "WHILE",
      "PLUS +", "MINUS -", "TIMES *", "TRUE",
      "LT <", "LEQ <=", "GT >", "GEQ >=", "EQ ==", "NEQ <>", "COLON :", "SEMI ;",
      "COMMA ,", "SHARP #", "DOT .", "LP (", "RP )", "LB "+'{', "RB "+'}', "LSB [", "RSB ]"
    };

    public static String print ( Symbol s ) {
        for ( int i = 0; i < tokens.length; i++ ) {
            if (tokens[i] == s.sym) {
                String res = token_names[i] + " ";
                if (s.value == null)
                    return res;
                else if (s.value instanceof Integer)
                    return res + ((Integer) s.value).intValue();
                else if (s.value instanceof Float)
                    return res + ((Float) s.value).floatValue();
                else if (s.value instanceof String)
                    return res + "\"" + (String) s.value + "\"";
            }
        };
        return "?";
    }

    public void syntax_error ( Symbol token ) {
        System.err.println("*** Syntax Error: " + print(token) + " (line: " + token.left
                           + ", column: " + token.right + ")");
        System.exit(1);
    }

    /** nil is the empty list */
    final static List nil = Nil$.MODULE$;

    /** Append list2 at the end of list1 (ie, return a new list containing
        the elements from list1 followed by the elements from list2) */
    static<T> List<T> append ( List<T> list1, List<T> list2 ) {
        return list1.$colon$colon$colon(list2);
    }

    /** append the element elem at the end of the list
       (ie, return a new list containing the list followed by the elem) */
    static<T> List<T> append ( List<T> list, T elem ) {
        return nil.$colon$colon(elem).$colon$colon$colon(list);
    }

    /** Insert the element elem at the beginning of the list
        (ie, return a new list containing the elem followed by the list) */
    static<T> List<T> add ( T elem, List<T> list ) {
        return list.$colon$colon(elem);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SplParser$actions {
  private final SplParser parser;

  /** Constructor */
  CUP$SplParser$actions(SplParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SplParser$do_action_part00000000(
    int                        CUP$SplParser$act_num,
    java_cup.runtime.lr_parser CUP$SplParser$parser,
    java.util.Stack            CUP$SplParser$stack,
    int                        CUP$SplParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SplParser$result;

      /* select the action based on the action number */
      switch (CUP$SplParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		RESULT = start_val;
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SplParser$parser.done_parsing();
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= block_content 
            {
              Program RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		BlockSt b = (BlockSt)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 SPL.setAST(new Program(b)); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // block_content ::= defs stmts 
            {
              BlockSt RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Definition> dl = (List<Definition>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		int slleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int slright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Stmt> sl = (List<Stmt>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new BlockSt(dl, sl); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("block_content",1, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // block_content ::= stmts 
            {
              BlockSt RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int slright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Stmt> sl = (List<Stmt>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new BlockSt(nil, sl); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("block_content",1, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // defs ::= declaration SEMI 
            {
              List<Definition> RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		Definition d = (Definition)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = append(nil, d); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("defs",3, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // defs ::= declaration SEMI defs 
            {
              List<Definition> RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Definition d = (Definition)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int dlleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Definition> dl = (List<Definition>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(dl, d); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("defs",3, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaration ::= VAR ID optionalType EQUAL expr 
            {
              Definition RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new VarDef(name, t, e); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("declaration",4, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaration ::= TYPE ID EQUAL type 
            {
              Definition RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new TypeDef(name, t); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("declaration",4, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaration ::= DEF ID LP parameterList RP optionalType LB block_content RB 
            {
              Definition RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-7)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-7)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-7)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-5)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-5)).right;
		List<Bind<Type>> params = (List<Bind<Type>>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-5)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		BlockSt b = (BlockSt)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new FuncDef(name, params, t, b); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("declaration",4, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-8)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // optionalType ::= 
            {
              Type RESULT =null;
		 RESULT = new AnyType(); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("optionalType",12, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // optionalType ::= COLON type 
            {
              Type RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = t; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("optionalType",12, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // parameterList ::= ID COLON type COMMA parameterList 
            {
              List<Bind<Type>> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Bind<Type>> params = (List<Bind<Type>>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(params, new Bind<Type>(name, t)); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("parameterList",13, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // parameterList ::= ID COLON type 
            {
              List<Bind<Type>> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(nil, new Bind<Type>(name, t)); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("parameterList",13, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // parameterList ::= 
            {
              List<Bind<Type>> RESULT =null;
		 RESULT = nil; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("parameterList",13, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= INTEGER_LITERAL 
            {
              Expr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new IntConst(n); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= FLOAT_LITERAL 
            {
              Expr RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Float f = (Float)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new FloatConst(f); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= STRING_LITERAL 
            {
              Expr RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new StringConst(s); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= TRUE 
            {
              Expr RESULT =null;
		 RESULT = new BooleanConst(true); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= FALSE 
            {
              Expr RESULT =null;
		 RESULT = new BooleanConst(false); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= lvalue 
            {
              Expr RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Lvalue lv = (Lvalue)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new LvalExp(lv); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= LSB expressionList RSB 
            {
              Expr RESULT =null;
		int exprsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int exprsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Expr> exprs = (List<Expr>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new ArrayExp(exprs); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= ID LP expressionList RP 
            {
              Expr RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Expr> args = (List<Expr>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new CallExp(name, args); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= unaryOperator expr 
            {
              Expr RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new UnOpExp(op, e); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= expr binaryOperator expr 
            {
              Expr RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Expr e2 = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e3 = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new BinOpExp(op, e2, e3); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= LP expressionList RP 
            {
              Expr RESULT =null;
		int exprsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int exprsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Expr> exprs = (List<Expr>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new TupleExp(exprs); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= ARRAY LP expr COMMA expr RP 
            {
              Expr RESULT =null;
		int lengthleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).left;
		int lengthright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).right;
		Expr length = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		Expr value = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new ArrayGen(length, value); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-5)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= LB componentList RB 
            {
              Expr RESULT =null;
		int componentsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int componentsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Bind<Expr>> components = (List<Bind<Expr>>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new RecordExp(components); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expressionList ::= expr COMMA expressionList 
            {
              List<Expr> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int elright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Expr> el = (List<Expr>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(el, e); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expressionList",11, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expressionList ::= expr 
            {
              List<Expr> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(nil, e); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expressionList",11, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expressionList ::= 
            {
              List<Expr> RESULT =null;
		 RESULT = nil; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("expressionList",11, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // typeList ::= type COMMA typeList 
            {
              List<Type> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int tlleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int tlright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Type> tl = (List<Type>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(tl, t); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("typeList",15, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // typeList ::= type 
            {
              List<Type> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(nil, t); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("typeList",15, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // stmts ::= stmt SEMI 
            {
              List<Stmt> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = append(nil, s); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmts",6, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // stmts ::= stmt SEMI stmts 
            {
              List<Stmt> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int slleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int slright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Stmt> sl = (List<Stmt>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(sl, s); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmts",6, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // stmt ::= lvalue EQUAL expr 
            {
              Stmt RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Lvalue l = (Lvalue)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new AssignSt(l, e); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // stmt ::= ID LP expressionList RP 
            {
              Stmt RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Expr> args = (List<Expr>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new CallSt(name, args); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // stmt ::= LB block_content RB 
            {
              Stmt RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		BlockSt b = (BlockSt)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = b; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // stmt ::= READ LP lvalueList RP 
            {
              Stmt RESULT =null;
		int argsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Lvalue> args = (List<Lvalue>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new ReadSt(args); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // stmt ::= PRINT LP expressionList RP 
            {
              Stmt RESULT =null;
		int argsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Expr> args = (List<Expr>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new PrintSt(args); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // stmt ::= IF LP expr RP stmt 
            {
              Stmt RESULT =null;
		int conditionleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int conditionright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Expr condition = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int then_stmtleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int then_stmtright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Stmt then_stmt = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new IfSt(condition, then_stmt, null); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // stmt ::= IF LP expr RP stmt ELSE stmt 
            {
              Stmt RESULT =null;
		int conditionleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).left;
		int conditionright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).right;
		Expr condition = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).value;
		int then_stmtleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int then_stmtright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Stmt then_stmt = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int else_stmtleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int else_stmtright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Stmt else_stmt = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new IfSt(condition, then_stmt, else_stmt); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-6)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // stmt ::= FOR LP ID EQUAL expr TO expr elseClause RP stmt 
            {
              Stmt RESULT =null;
		int varNameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-7)).left;
		int varNameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-7)).right;
		String varName = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-7)).value;
		int initialleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-5)).left;
		int initialright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-5)).right;
		Expr initial = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-5)).value;
		int limitleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).left;
		int limitright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).right;
		Expr limit = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).value;
		int stepleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Expr step = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Stmt body = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new ForSt(varName, initial, step, limit, body); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-9)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // stmt ::= WHILE LP expr RP stmt 
            {
              Stmt RESULT =null;
		int conditionleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int conditionright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Expr condition = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Stmt body = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new WhileSt(condition, body); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // stmt ::= LOOP stmt 
            {
              Stmt RESULT =null;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Stmt body = (Stmt)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new LoopSt(body); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // stmt ::= EXIT 
            {
              Stmt RESULT =null;
		 RESULT = new ExitSt(); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // stmt ::= RETURN expr 
            {
              Stmt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new ReturnValueSt(e); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // stmt ::= RETURN 
            {
              Stmt RESULT =null;
		 RESULT = new ReturnSt(); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // elseClause ::= BY expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = e; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("elseClause",14, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // elseClause ::= 
            {
              Expr RESULT =null;
		 RESULT = new IntConst(1); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("elseClause",14, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // lvalueList ::= lvalue COMMA lvalueList 
            {
              List<Lvalue> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Lvalue l = (Lvalue)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int llleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int llright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Lvalue> ll = (List<Lvalue>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(ll, l); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("lvalueList",16, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // lvalueList ::= lvalue 
            {
              List<Lvalue> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Lvalue l = (Lvalue)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(nil, l); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("lvalueList",16, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // lvalue ::= ID 
            {
              Lvalue RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new Var(name); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("lvalue",8, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // lvalue ::= lvalue LSB expr RSB 
            {
              Lvalue RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).right;
		Lvalue lv = (Lvalue)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)).value;
		int indexleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int indexright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		Expr index = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new ArrayDeref(new LvalExp(lv), index); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("lvalue",8, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // lvalue ::= lvalue DOT ID 
            {
              Lvalue RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Lvalue lv = (Lvalue)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int fieldleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int fieldright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		String field = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new RecordDeref(new LvalExp(lv), field); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("lvalue",8, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // lvalue ::= lvalue SHARP INTEGER_LITERAL 
            {
              Lvalue RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Lvalue lv = (Lvalue)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new TupleDeref(new LvalExp(lv), i); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("lvalue",8, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // componentList ::= ID EQUAL expr COMMA componentList 
            {
              List<Bind<Expr>> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int clright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		List<Bind<Expr>> cl = (List<Bind<Expr>>)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(cl, new Bind<Expr>(name, e)); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("componentList",17, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-4)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // componentList ::= ID EQUAL expr 
            {
              List<Bind<Expr>> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = append(nil, new Bind<Expr>(name, e)); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("componentList",17, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // unaryOperator ::= MINUS 
            {
              String RESULT =null;
		 RESULT = "-"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("unaryOperator",9, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // unaryOperator ::= NOT 
            {
              String RESULT =null;
		 RESULT = "not"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("unaryOperator",9, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // binaryOperator ::= PLUS 
            {
              String RESULT =null;
		 RESULT = "+"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // binaryOperator ::= MINUS 
            {
              String RESULT =null;
		 RESULT = "-"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // binaryOperator ::= TIMES 
            {
              String RESULT =null;
		 RESULT = "*"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // binaryOperator ::= DIV 
            {
              String RESULT =null;
		 RESULT = "/"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // binaryOperator ::= MOD 
            {
              String RESULT =null;
		 RESULT = "%"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // binaryOperator ::= AND 
            {
              String RESULT =null;
		 RESULT = "and"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // binaryOperator ::= OR 
            {
              String RESULT =null;
		 RESULT = "or"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // binaryOperator ::= EQ 
            {
              String RESULT =null;
		 RESULT = "=="; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // binaryOperator ::= NEQ 
            {
              String RESULT =null;
		 RESULT = "!="; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // binaryOperator ::= LT 
            {
              String RESULT =null;
		 RESULT = "<"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // binaryOperator ::= LEQ 
            {
              String RESULT =null;
		 RESULT = "<="; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // binaryOperator ::= GT 
            {
              String RESULT =null;
		 RESULT = ">"; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // binaryOperator ::= GEQ 
            {
              String RESULT =null;
		 RESULT = ">="; 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("binaryOperator",10, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // type ::= INT 
            {
              Type RESULT =null;
		 RESULT = new IntType(); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // type ::= FLOAT 
            {
              Type RESULT =null;
		 RESULT = new FloatType(); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // type ::= STRING 
            {
              Type RESULT =null;
		 RESULT = new StringType(); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // type ::= BOOLEAN 
            {
              Type RESULT =null;
		 RESULT = new BooleanType(); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // type ::= LB parameterList RB 
            {
              Type RESULT =null;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Bind<Type>> params = (List<Bind<Type>>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new RecordType(params); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // type ::= LP typeList RP 
            {
              Type RESULT =null;
		int typesleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int typesright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		List<Type> types = (List<Type>)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new TupleType(types); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-2)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // type ::= ARRAY LSB type RSB 
            {
              Type RESULT =null;
		int elemTypeleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).left;
		int elemTyperight = ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).right;
		Type elemType = (Type)((java_cup.runtime.Symbol) CUP$SplParser$stack.elementAt(CUP$SplParser$top-1)).value;
		 RESULT = new ArrayType(elemType); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.elementAt(CUP$SplParser$top-3)), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // type ::= ID 
            {
              Type RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$SplParser$stack.peek()).value;
		 RESULT = new NamedType(name); 
              CUP$SplParser$result = parser.getSymbolFactory().newSymbol("type",2, ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SplParser$stack.peek()), RESULT);
            }
          return CUP$SplParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SplParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SplParser$do_action(
    int                        CUP$SplParser$act_num,
    java_cup.runtime.lr_parser CUP$SplParser$parser,
    java.util.Stack            CUP$SplParser$stack,
    int                        CUP$SplParser$top)
    throws java.lang.Exception
    {
              return CUP$SplParser$do_action_part00000000(
                               CUP$SplParser$act_num,
                               CUP$SplParser$parser,
                               CUP$SplParser$stack,
                               CUP$SplParser$top);
    }
}

}
